INSERT INTO TASKS (DESCRIPTION, STATUS) VALUES ('Tarea uno', 'Completada');
INSERT INTO TASKS (DESCRIPTION, STATUS) VALUES ('Tarea dos', 'En proceso');
INSERT INTO TASKS (DESCRIPTION, STATUS) VALUES ('Tarea tres', 'Pendiente');